import {describe, expect, test} from 'bun:test';

import {formatText} from '../src/index.js';

describe('format_text', () => {
	test('wraps over-width line comment paragraphs', () => {
		const result = formatText({
			text: [
				'// This comment is far too long for the configured width and should be wrapped into multiple line comments.',
				'const value = 1;',
			].join('\n'),
			width: 50,
			tabWidth: 2,
		});

		expect(result).toEqual({
			changed: true,
			text: [
				'// This comment is far too long for the configured',
				'// width and should be wrapped into multiple line',
				'// comments.',
				'const value = 1;',
			].join('\n'),
		});
	});

	test('preserves indentation when wrapping line comments', () => {
		const result = formatText({
			text: [
				'\t// This comment is far too long for the configured width and should be wrapped.',
				'\tconst value = 1;',
			].join('\n'),
			width: 50,
			tabWidth: 2,
		});

		expect(result.text).toBe(
			[
				'\t// This comment is far too long for the',
				'\t// configured width and should be wrapped.',
				'\tconst value = 1;',
			].join('\n'),
		);
	});

	test('converts safe block prose comments to line comments', () => {
		const result = formatText({
			text: [
				'/*',
				' * This block comment is plain prose and should use line comment style.',
				' */',
			].join('\n'),
			width: 50,
			tabWidth: 2,
		});

		expect(result).toEqual({
			changed: true,
			text: [
				'// This block comment is plain prose and should',
				'// use line comment style.',
			].join('\n'),
		});
	});

	test('leaves directives and urls unchanged', () => {
		const text = [
			'// oxlint-disable-next-line no-console -- this directive is intentionally long and should not be wrapped.',
			'// https://example.com/a/really/long/path/that/should/not/be/wrapped',
		].join('\n');

		expect(
			formatText({
				text,
				width: 50,
				tabWidth: 2,
			}),
		).toEqual({changed: false, text});
	});

	test('leaves jsdoc comments unchanged for oxfmt', () => {
		const text = [
			'/**',
			' * This JSDoc comment is intentionally long because oxfmt owns JSDoc formatting.',
			' */',
		].join('\n');

		expect(
			formatText({
				text,
				width: 50,
				tabWidth: 2,
			}),
		).toEqual({changed: false, text});
	});

	test('leaves generated files unchanged', () => {
		const text = [
			'// Generated by a local tool.',
			'// This comment is very long and would otherwise be wrapped by the formatter.',
		].join('\n');

		expect(
			formatText({
				text,
				width: 50,
				tabWidth: 2,
			}),
		).toEqual({changed: false, text});
	});
});
