import {describe, expect, test} from 'bun:test';

import {measureLineWidth, scanText} from '../src/index.js';

describe('measure_line_width', () => {
	test('expands tabs to the configured tab stop', () => {
		expect(measureLineWidth('\t// hi', 2)).toBe(7);
		expect(measureLineWidth('\t// hi', 4)).toBe(9);
	});

	test('counts wide unicode display width', () => {
		expect(measureLineWidth('// 你好', 2)).toBe(7);
	});
});

describe('scan_text', () => {
	test('reports over-width line comments', () => {
		const result = scanText({
			file: 'src/demo.ts',
			text: '// This comment is too long for the tiny configured width.',
			width: 20,
			tabWidth: 2,
		});

		expect(result.violations).toEqual([
			{
				kind: 'width',
				file: 'src/demo.ts',
				line: 1,
				columnWidth: 58,
				maxWidth: 20,
				text: '// This comment is too long for the tiny configured width.',
			},
		]);
	});

	test('reports over-width block comment lines', () => {
		const result = scanText({
			file: 'src/demo.ts',
			text: '/**\n * This comment is too long for the tiny configured width.\n */',
			width: 20,
			tabWidth: 2,
		});

		expect(result.violations).toHaveLength(1);
		expect(result.violations[0]?.line).toBe(2);
	});

	test('ignores code lines with trailing comments', () => {
		const result = scanText({
			file: 'src/demo.ts',
			text: 'const value = 1; // This trailing comment is intentionally long.',
			width: 20,
			tabWidth: 2,
		});

		expect(result.violations).toEqual([]);
	});

	test('ignores url comments', () => {
		const result = scanText({
			file: 'src/demo.ts',
			text: '// https://example.com/a/really/long/path/that/exceeds/the/width',
			width: 20,
			tabWidth: 2,
		});

		expect(result.violations).toEqual([]);
	});

	test('ignores generated files', () => {
		const result = scanText({
			file: 'src/generated.ts',
			text: '// Generated by a local tool.\n// This comment is very long and would otherwise be reported.',
			width: 20,
			tabWidth: 2,
		});

		expect(result).toEqual({linesChecked: 0, violations: []});
	});
});
