import type {Violation} from './types.js';
import {measureLineWidth} from './width.js';

const URL_PATTERN = /\b[a-z][a-z\d+.-]*:\/\/\S+/iu;
const GENERATED_PATTERN =
	/\b(@generated|auto-generated|automatically generated|code generated|do not edit|generated by)\b/iu;

/**
 * It is the input needed to scan one source file's text.
 */
export type ScanTextOptions = {
	/**
	 * Repo-relative file path used in diagnostics.
	 */
	file: string;
	/**
	 * Source text to scan.
	 */
	text: string;
	/**
	 * Maximum visual columns allowed for a comment line.
	 */
	width: number;
	/**
	 * Number of visual columns between tab stops.
	 */
	tabWidth: number;
};

/**
 * It is the result from scanning one source file.
 */
export type ScanTextResult = {
	/**
	 * Number of full-line comments checked.
	 */
	linesChecked: number;
	/**
	 * Over-width comment lines found during scanning.
	 */
	violations: Violation[];
};

/**
 * Reports over-width full-line comments from one source file.
 */
export function scanText(options: ScanTextOptions): ScanTextResult {
	if (isGeneratedFile(options.text)) {
		return {linesChecked: 0, violations: []};
	}

	const violations: Violation[] = [];
	const lines = options.text.split(/\r?\n/u);
	let linesChecked = 0;

	for (const [index, line] of lines.entries()) {
		const trimmed = line.trimStart();

		if (!isCommentOnlyLine(trimmed) || URL_PATTERN.test(trimmed)) {
			continue;
		}

		linesChecked++;

		if (line.length <= options.width) {
			continue;
		}

		const columnWidth = measureLineWidth(line, options.tabWidth);

		if (columnWidth <= options.width) {
			continue;
		}

		violations.push({
			file: options.file,
			line: index + 1,
			columnWidth,
			maxWidth: options.width,
			text: line.trim(),
		});
	}

	return {linesChecked, violations};
}

/**
 * Returns true when a trimmed line is a standalone comment line.
 */
export function isCommentOnlyLine(trimmedLine: string): boolean {
	return (
		trimmedLine.startsWith('//') ||
		trimmedLine.startsWith('/*') ||
		trimmedLine.startsWith('*')
	);
}

/**
 * Returns true when a source file advertises itself as generated.
 */
export function isGeneratedFile(text: string): boolean {
	const header = text.split(/\r?\n/u).slice(0, 5).join('\n');

	return GENERATED_PATTERN.test(header);
}
